CREATE TABLE IF NOT EXISTS atributo_valor (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    atributo_id INT NOT NULL,
    valor VARCHAR(255) NOT NULL,

    UNIQUE KEY uk_atributo_valor (atributo_id, valor),

    CONSTRAINT fk_atributo_valores_atributo FOREIGN KEY (atributo_id) REFERENCES atributos(id) ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT INTO atributo_valor (atributo_id, valor) VALUES
                                                    (1, 'S'),
                                                    (1, 'M'),
                                                    (1, 'L'),
                                                    (1, 'XL'),
                                                    (1, '32'),
                                                    (1, '34'),
                                                    (1, '36'),
                                                    (1, '40'),
                                                    (1, '41'),
                                                    (1, '41.5'),
                                                    (1, '42'),
                                                    (1, '42.5'),
                                                    (1, '43'),
                                                    (1, '44'),
                                                    (1, '45'),
                                                    (2, '1'),
                                                    (2, '1.25'),
                                                    (2, '1.5'),
                                                    (2, '2'),
                                                    (2, '2.5'),
                                                    (2, '3'),
                                                    (2, '4'),
                                                    (2, '5'),
                                                    (3, '100'),
                                                    (3, '250'),
                                                    (3, '500'),
                                                    (3, '750'),
                                                    (3, '1000'),
                                                    (3, '1500'),
                                                    (3, '2000'),
                                                    (3, '2500'),
                                                    (4, 'Negro'),
                                                    (4, 'Blanco'),
                                                    (4, 'Rojo'),
                                                    (4, 'Azul'),
                                                    (4, 'Amarillo'),
                                                    (4, 'Anaranjado'),
                                                    (4, 'Gris'),
                                                    (4, 'Verde');