CREATE TABLE IF NOT EXISTS documento (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
	numero TEXT NOT NULL,
    usuario_id INTEGER NOT NULL,
    cliente_id INTEGER,
    fecha_emision TEXT NOT NULL,
    fecha_vencimiento TEXT,
    fecha_actualizacion TEXT,
    tipo_documento_id INTEGER NOT NULL,
    almacen_id INTEGER NOT NULL,
    nota TEXT,
    estado INTEGER NOT NULL,
    impuesto NUMERIC,
    sub_total NUMERIC,
    total NUMERIC,
    proveedor_id INTEGER,
    FOREIGN KEY (usuario_id) REFERENCES usuario (id)  ON DELETE CASCADE,
    FOREIGN KEY (cliente_id) REFERENCES cliente (id)  ON DELETE CASCADE,
    FOREIGN KEY (proveedor_id) REFERENCES proveedor (id)  ON DELETE CASCADE,
    FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id)  ON DELETE CASCADE,
    FOREIGN KEY (almacen_id) REFERENCES almacen (id)  ON DELETE CASCADE
);