CREATE TABLE IF NOT EXISTS Producto (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,

    Codigo TEXT NOT NULL UNIQUE,
    CodigoBarra TEXT DEFAULT NULL,
    Nombre TEXT NOT NULL,

    UnidadMedida TEXT DEFAULT NULL,
    Modelo TEXT DEFAULT NULL,
    Serie TEXT DEFAULT NULL,

    MarcaID INTEGER DEFAULT NULL,
    CategoriaID INTEGER DEFAULT NULL,
    ProveedorID INTEGER DEFAULT NULL,

    PrecioCosto REAL NOT NULL,
    Utilidad INTEGER DEFAULT 0,

    Precio1 REAL NOT NULL,
    Precio2 REAL NOT NULL,
    Precio3 REAL NOT NULL,

    CantMayor INTEGER DEFAULT NULL,

    PrecioIncluyeImpuesto INTEGER NOT NULL DEFAULT 1,
    Disponible INTEGER NOT NULL DEFAULT 1,

    CantidadDisponible INTEGER DEFAULT NULL,
    StockCritico INTEGER DEFAULT NULL,

    NoRequiereStock INTEGER NOT NULL DEFAULT 0,
    ReqAprobPrecioEspecial INTEGER NOT NULL DEFAULT 1,

    FechaActualizacion TEXT DEFAULT NULL,
    FechaCreado TEXT DEFAULT CURRENT_TIMESTAMP,

    Nota TEXT DEFAULT NULL,

    FOREIGN KEY (CategoriaID) REFERENCES Categoria (ID) ON DELETE CASCADE,
    FOREIGN KEY (MarcaID) REFERENCES Marca (ID) ON DELETE CASCADE,
    FOREIGN KEY (ProveedorID) REFERENCES Proveedor (ID) ON DELETE CASCADE
);