CREATE TABLE IF NOT EXISTS DocumentoItem (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
    DocumentoID INTEGER NOT NULL,
    ProductoID INTEGER NOT NULL,
    Cantidad NUMERIC NOT NULL DEFAULT(0),
    PrecioUnitario NUMERIC,
    PrecioNeto NUMERIC,
    PrecioTotal NUMERIC NULL DEFAULT(0),
    FOREIGN KEY (DocumentoID) REFERENCES Documento (ID)  ON DELETE CASCADE,
    FOREIGN KEY (ProductoID) REFERENCES Producto (ID)  ON DELETE CASCADE
);