CREATE TABLE IF NOT EXISTS Stock (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,
    ProductoID INTEGER NOT NULL,
    AlmacenID INTEGER NOT NULL,
	Cantidad NUMERIC NOT NULL,
  FOREIGN KEY (ProductoID) REFERENCES Producto (id) ON DELETE CASCADE,
  FOREIGN KEY (AlmacenID) REFERENCES Almacen (id) ON DELETE CASCADE
);